sudo: required
language: node_js
node_js:
  - "9"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install -g gulp-cli
script:
  - npm run lint
  - npm run build:prod
  - npm run test
